name: diettest2
description: A new Flutter project.


publish_to: 'none'

version: 1.0.1+2

environment:
  # sdk: "3.2.0"
 sdk: ">=3.2.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons:
  firebase_core: ^2.22.0
  cloud_firestore: ^4.13.1
  firebase_auth:
  firebase_core_platform_interface:
  firebase_messaging:
  firebase_storage:
  firebase_database:
  google_fonts: ^6.1.0
  date_picker_timeline:
  google_nav_bar:
  rename: ^3.0.1
  animations:
  get:
  provider:
  percent_indicator:
  line_icons:
  flutter_svg:
  geolocator:
  geocoding:
  permission_handler:
  youtube_player_flutter:
  connectivity:
  flutter_signin_button:
  change_app_package_name: ^1.1.0
  fluttertoast: ^8.2.4
  cached_network_image: ^3.3.0
  flutter_staggered_grid_view: ^0.7.0
  image_picker: ^1.0.4
  rename_app: ^1.3.1
  app_settings: ^5.1.1
  url_launcher: ^6.2.2
  ionicons: ^0.2.2
#  fluttertoast:





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon.png"
  min_sdk_android: 21 

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - images/
    - assets/utiles/
    - assets/profilepage/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
